# Generated by Django 3.2 on 2024-05-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendordetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('contact_details', models.TextField(max_length=100)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=7, max_digits=15)),
                ('quality_rating_avg', models.DecimalField(decimal_places=7, max_digits=15)),
                ('average_response_time', models.DecimalField(decimal_places=7, max_digits=15)),
                ('fulfillment_rate', models.DecimalField(decimal_places=7, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='vendor_Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=7, max_digits=15)),
                ('quality_rating_avg', models.DecimalField(decimal_places=7, max_digits=15)),
                ('average_response_time', models.DecimalField(decimal_places=7, max_digits=15)),
                ('fulfillment_rate', models.DecimalField(decimal_places=7, max_digits=15)),
                ('vendor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorTask.vendordetails')),
            ],
        ),
        migrations.CreateModel(
            name='purchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('quality_rating', models.DecimalField(decimal_places=7, max_digits=15)),
                ('issue_date', models.DateTimeField()),
                ('acknowledgment_date', models.DateTimeField()),
                ('vendor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorTask.vendordetails')),
            ],
        ),
    ]
