# Generated by Django 3.2 on 2024-05-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorTask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=7, max_digits=15)),
                ('quality_rating_avg', models.DecimalField(decimal_places=7, max_digits=15)),
                ('average_response_time', models.DecimalField(decimal_places=7, max_digits=15)),
                ('fulfillment_rate', models.DecimalField(decimal_places=7, max_digits=15)),
            ],
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseOrder', to='vendorTask.vendordetails'),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='contact_details',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='vendor_Performance',
        ),
        migrations.AddField(
            model_name='vendorperformance',
            name='vendor_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VendorPerformance', to='vendorTask.vendordetails'),
        ),
    ]
