# Generated by Django 3.2 on 2024-05-14 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorTask', '0002_auto_20240512_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorTask.vendordetails'),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='vendor_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendorperformance',
            name='vendor_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorTask.vendordetails'),
        ),
    ]
