# Generated by Django 3.2 on 2024-05-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorTask', '0004_auto_20240514_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='quality_rating',
            field=models.BooleanField(),
        ),
    ]
