# Generated by Django 3.2 on 2024-05-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorTask', '0005_alter_purchaseorder_quality_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='rain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quality_rating',
            field=models.DecimalField(decimal_places=7, max_digits=15),
        ),
    ]
