# Generated by Django 3.2 on 2024-05-19 01:36
from django.db import migrations, models

def convert_numeric_to_boolean(apps, schema_editor):
    PurchaseOrder = apps.get_model('vendorTask', 'PurchaseOrder')
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE vendorTask_purchaseorder
            SET quality_rating_new = CASE
                WHEN quality_rating = 1 THEN TRUE
                ELSE FALSE
            END
        """)

class Migration(migrations.Migration):

    dependencies = [
        ('vendorTask', '0006_auto_20240518_1839'),  # Adjust this to match the last migration file
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='quality_rating_new',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(convert_numeric_to_boolean),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quality_rating',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='quality_rating_new',
            new_name='quality_rating',
        ),
    ]
